In [7]:
import tensorflow.keras
import segmentation_models as sm
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing.image import array_to_img
from tensorflow.keras.models import load_model

import os
import cv2
import numpy as np
import random

In [2]:
import tensorflow.keras
# or from tensorflow import keras

tensorflow.keras.backend.set_image_data_format('channels_last')
# or keras.backend.set_image_data_format('channels_first')

In [3]:
# Load pre trained PSPNet segmentation model

model = sm.PSPNet()

In [4]:
# Set the model parameters

model = sm.PSPNet('resnet34', classes=1, activation='sigmoid', encoder_weights='imagenet', input_shape=(240, 240, 3))

In [49]:
# Change the dataset directory in which photos + mask of a location are stored
directory = "1093"

In [50]:
dim = 0

for root, dirs, files in os.walk(directory + "/"):
    for file in files:
        if file.endswith(".jpg"):
            dim=dim+1
        
print("dim: ", dim)

# change the first value(300 here) to the number of images to sample from the folder 
images_array = np.empty([300, 57600, 3], dtype="float")

i=0;


for root, dirs, files in os.walk(directory + "/"):
    for file in files:
        if file.endswith(".jpg"):
            img_path = os.path.join(root, file)
            img = cv2.imread(img_path)
            # image resolution is downscaled to 240 * 240 pixels
            res = cv2.resize(img, dsize=(240, 240), interpolation=cv2.INTER_CUBIC)
            img_array = img_to_array(res)
            # 57600 = 240*240 and 3 represents the number of color channels
            img_array = img_array.reshape(57600, 3)
            images_array[i] = img_array
            print("\n\nImages: ", images_array[i], "\n", i, " : ", img_array)
            i=i+1
            print("i", i)
            # i=300 means it'll take the first 300 images' data which will later be assignes as 240 for training and 60 as testing
            if(i==300):
                break

dim:  870


Images:  [[177. 176. 156.]
 [178. 176. 156.]
 [179. 178. 158.]
 ...
 [ 54.  74.  83.]
 [ 61.  87.  94.]
 [ 78. 106. 113.]] 
 0  :  [[177. 176. 156.]
 [178. 176. 156.]
 [179. 178. 158.]
 ...
 [ 54.  74.  83.]
 [ 61.  87.  94.]
 [ 78. 106. 113.]]
i 1


Images:  [[ 40.  16.  26.]
 [ 49.  27.  40.]
 [ 39.  20.  35.]
 ...
 [170. 158. 169.]
 [172. 172. 182.]
 [116. 126. 134.]] 
 1  :  [[ 40.  16.  26.]
 [ 49.  27.  40.]
 [ 39.  20.  35.]
 ...
 [170. 158. 169.]
 [172. 172. 182.]
 [116. 126. 134.]]
i 2


Images:  [[ 96.  84.  79.]
 [106.  80.  77.]
 [108.  84.  81.]
 ...
 [167. 156. 174.]
 [173. 164. 174.]
 [151. 145. 146.]] 
 2  :  [[ 96.  84.  79.]
 [106.  80.  77.]
 [108.  84.  81.]
 ...
 [167. 156. 174.]
 [173. 164. 174.]
 [151. 145. 146.]]
i 3


Images:  [[246. 131.  75.]
 [244. 129.  73.]
 [244. 128.  73.]
 ...
 [148. 139. 144.]
 [150. 145. 145.]
 [133. 129. 126.]] 
 3  :  [[246. 131.  75.]
 [244. 129.  73.]
 [244. 128.  73.]
 ...
 [148. 139. 144.]
 [150. 145. 145.]
 [133. 12



Images:  [[48. 25. 20.]
 [25. 24. 29.]
 [11. 16. 20.]
 ...
 [35. 29. 53.]
 [32. 39. 47.]
 [21. 40. 32.]] 
 44  :  [[48. 25. 20.]
 [25. 24. 29.]
 [11. 16. 20.]
 ...
 [35. 29. 53.]
 [32. 39. 47.]
 [21. 40. 32.]]
i 45


Images:  [[226. 226. 226.]
 [227. 227. 227.]
 [228. 228. 228.]
 ...
 [106. 123. 131.]
 [126. 144. 150.]
 [ 93. 112. 117.]] 
 45  :  [[226. 226. 226.]
 [227. 227. 227.]
 [228. 228. 228.]
 ...
 [106. 123. 131.]
 [126. 144. 150.]
 [ 93. 112. 117.]]
i 46


Images:  [[211. 148.  88.]
 [211. 145.  90.]
 [218. 146.  97.]
 ...
 [ 89.  87.  73.]
 [ 98. 100.  70.]
 [ 83.  85.  42.]] 
 46  :  [[211. 148.  88.]
 [211. 145.  90.]
 [218. 146.  97.]
 ...
 [ 89.  87.  73.]
 [ 98. 100.  70.]
 [ 83.  85.  42.]]
i 47


Images:  [[ 37.  18.  20.]
 [ 37.  26.  31.]
 [ 17.  16.  23.]
 ...
 [173. 167. 165.]
 [172. 170. 171.]
 [167. 165. 170.]] 
 47  :  [[ 37.  18.  20.]
 [ 37.  26.  31.]
 [ 17.  16.  23.]
 ...
 [173. 167. 165.]
 [172. 170. 171.]
 [167. 165. 170.]]
i 48


Images:  [[167. 172. 1



Images:  [[216. 214. 213.]
 [217. 214. 213.]
 [218. 214. 213.]
 ...
 [ 91. 104. 102.]
 [ 33.  45.  45.]
 [ 26.  37.  41.]] 
 83  :  [[216. 214. 213.]
 [217. 214. 213.]
 [218. 214. 213.]
 ...
 [ 91. 104. 102.]
 [ 33.  45.  45.]
 [ 26.  37.  41.]]
i 84


Images:  [[199. 181. 174.]
 [200. 182. 175.]
 [201. 183. 176.]
 ...
 [ 88. 102. 123.]
 [103. 119. 133.]
 [108. 127. 134.]] 
 84  :  [[199. 181. 174.]
 [200. 182. 175.]
 [201. 183. 176.]
 ...
 [ 88. 102. 123.]
 [103. 119. 133.]
 [108. 127. 134.]]
i 85


Images:  [[ 94.  73.  55.]
 [ 90.  74.  60.]
 [ 91.  81.  70.]
 ...
 [ 99. 102. 102.]
 [ 92.  95.  95.]
 [ 94. 100. 100.]] 
 85  :  [[ 94.  73.  55.]
 [ 90.  74.  60.]
 [ 91.  81.  70.]
 ...
 [ 99. 102. 102.]
 [ 92.  95.  95.]
 [ 94. 100. 100.]]
i 86


Images:  [[162. 153. 139.]
 [162. 153. 139.]
 [162. 153. 139.]
 ...
 [ 63.  76.  86.]
 [ 82. 100. 101.]
 [ 75.  99.  92.]] 
 86  :  [[162. 153. 139.]
 [162. 153. 139.]
 [162. 153. 139.]
 ...
 [ 63.  76.  86.]
 [ 82. 100. 101.]
 [ 75.  99. 



Images:  [[ 37.  14.  29.]
 [ 50.  38.  55.]
 [ 10.  12.  29.]
 ...
 [147. 148. 142.]
 [155. 156. 148.]
 [129. 132. 122.]] 
 123  :  [[ 37.  14.  29.]
 [ 50.  38.  55.]
 [ 10.  12.  29.]
 ...
 [147. 148. 142.]
 [155. 156. 148.]
 [129. 132. 122.]]
i 124


Images:  [[ 25.  44.  25.]
 [ 38.  40.  36.]
 [ 53.  34.  46.]
 ...
 [140. 143. 143.]
 [159. 165. 157.]
 [123. 133. 120.]] 
 124  :  [[ 25.  44.  25.]
 [ 38.  40.  36.]
 [ 53.  34.  46.]
 ...
 [140. 143. 143.]
 [159. 165. 157.]
 [123. 133. 120.]]
i 125


Images:  [[219. 217. 217.]
 [221. 219. 219.]
 [222. 220. 220.]
 ...
 [130. 141. 145.]
 [ 88. 100.  99.]
 [ 41.  54.  51.]] 
 125  :  [[219. 217. 217.]
 [221. 219. 219.]
 [222. 220. 220.]
 ...
 [130. 141. 145.]
 [ 88. 100.  99.]
 [ 41.  54.  51.]]
i 126


Images:  [[113.  92.  79.]
 [ 91.  79.  52.]
 [117. 106.  82.]
 ...
 [156. 150. 155.]
 [145. 138. 135.]
 [125. 117. 106.]] 
 126  :  [[113.  92.  79.]
 [ 91.  79.  52.]
 [117. 106.  82.]
 ...
 [156. 150. 155.]
 [145. 138. 135.]
 [125



Images:  [[180. 174. 175.]
 [182. 176. 177.]
 [185. 179. 180.]
 ...
 [ 63.  71.  78.]
 [ 79.  90.  93.]
 [ 84.  96.  98.]] 
 157  :  [[180. 174. 175.]
 [182. 176. 177.]
 [185. 179. 180.]
 ...
 [ 63.  71.  78.]
 [ 79.  90.  93.]
 [ 84.  96.  98.]]
i 158


Images:  [[ 25.  27.  27.]
 [ 43.  33.  28.]
 [ 53.  30.  18.]
 ...
 [173. 169. 170.]
 [179. 178. 177.]
 [151. 149. 148.]] 
 158  :  [[ 25.  27.  27.]
 [ 43.  33.  28.]
 [ 53.  30.  18.]
 ...
 [173. 169. 170.]
 [179. 178. 177.]
 [151. 149. 148.]]
i 159


Images:  [[ 28.  17.  15.]
 [ 29.  13.   6.]
 [ 39.  18.   3.]
 ...
 [172. 155. 161.]
 [183. 170. 173.]
 [167. 158. 158.]] 
 159  :  [[ 28.  17.  15.]
 [ 29.  13.   6.]
 [ 39.  18.   3.]
 ...
 [172. 155. 161.]
 [183. 170. 173.]
 [167. 158. 158.]]
i 160


Images:  [[183. 183. 183.]
 [184. 184. 184.]
 [185. 185. 185.]
 ...
 [ 94. 113. 118.]
 [110. 129. 132.]
 [ 95. 115. 117.]] 
 160  :  [[183. 183. 183.]
 [184. 184. 184.]
 [185. 185. 185.]
 ...
 [ 94. 113. 118.]
 [110. 129. 132.]
 [ 95

 [126. 148. 153.]] 
 192  :  [[209. 208. 210.]
 [211. 210. 212.]
 [211. 210. 212.]
 ...
 [108. 129. 152.]
 [132. 154. 166.]
 [126. 148. 153.]]
i 193


Images:  [[ 45.  17.  35.]
 [ 30.  20.  28.]
 [ 25.  18.  18.]
 ...
 [174. 173. 174.]
 [180. 182. 175.]
 [154. 155. 145.]] 
 193  :  [[ 45.  17.  35.]
 [ 30.  20.  28.]
 [ 25.  18.  18.]
 ...
 [174. 173. 174.]
 [180. 182. 175.]
 [154. 155. 145.]]
i 194


Images:  [[210. 205. 204.]
 [212. 207. 206.]
 [215. 210. 209.]
 ...
 [ 60.  70.  74.]
 [ 74.  86.  90.]
 [ 96. 108. 114.]] 
 194  :  [[210. 205. 204.]
 [212. 207. 206.]
 [215. 210. 209.]
 ...
 [ 60.  70.  74.]
 [ 74.  86.  90.]
 [ 96. 108. 114.]]
i 195


Images:  [[164. 155. 141.]
 [165. 156. 142.]
 [166. 157. 143.]
 ...
 [ 62.  79. 102.]
 [ 88. 115. 131.]
 [113. 149. 160.]] 
 195  :  [[164. 155. 141.]
 [165. 156. 142.]
 [166. 157. 143.]
 ...
 [ 62.  79. 102.]
 [ 88. 115. 131.]
 [113. 149. 160.]]
i 196


Images:  [[180. 175. 174.]
 [181. 176. 175.]
 [182. 177. 176.]
 ...
 [104. 116. 122.

 [ 58.  73.  75.]]
i 225


Images:  [[48. 27.  8.]
 [58. 23. 19.]
 [41. 15. 12.]
 ...
 [59. 41. 42.]
 [41. 38. 38.]
 [31. 39. 34.]] 
 225  :  [[48. 27.  8.]
 [58. 23. 19.]
 [41. 15. 12.]
 ...
 [59. 41. 42.]
 [41. 38. 38.]
 [31. 39. 34.]]
i 226


Images:  [[212. 206. 201.]
 [213. 207. 202.]
 [215. 209. 204.]
 ...
 [109. 121. 121.]
 [ 93. 106. 101.]
 [ 49.  62.  54.]] 
 226  :  [[212. 206. 201.]
 [213. 207. 202.]
 [215. 209. 204.]
 ...
 [109. 121. 121.]
 [ 93. 106. 101.]
 [ 49.  62.  54.]]
i 227


Images:  [[149. 140. 120.]
 [150. 141. 121.]
 [151. 142. 122.]
 ...
 [ 57.  94. 121.]
 [107. 153. 170.]
 [130. 184. 191.]] 
 227  :  [[149. 140. 120.]
 [150. 141. 121.]
 [151. 142. 122.]
 ...
 [ 57.  94. 121.]
 [107. 153. 170.]
 [130. 184. 191.]]
i 228


Images:  [[187. 151. 127.]
 [188. 152. 128.]
 [189. 153. 129.]
 ...
 [124. 153. 183.]
 [160. 189. 209.]
 [186. 212. 225.]] 
 228  :  [[187. 151. 127.]
 [188. 152. 128.]
 [189. 153. 129.]
 ...
 [124. 153. 183.]
 [160. 189. 209.]
 [186. 212. 225.



Images:  [[ 13.  17.   4.]
 [ 34.  15.  10.]
 [ 14.  19.  17.]
 ...
 [169. 166. 162.]
 [179. 175. 173.]
 [146. 138. 138.]] 
 267  :  [[ 13.  17.   4.]
 [ 34.  15.  10.]
 [ 14.  19.  17.]
 ...
 [169. 166. 162.]
 [179. 175. 173.]
 [146. 138. 138.]]
i 268


Images:  [[194. 189. 188.]
 [195. 190. 189.]
 [196. 191. 190.]
 ...
 [112. 120. 127.]
 [109. 117. 123.]
 [ 69.  77.  81.]] 
 268  :  [[194. 189. 188.]
 [195. 190. 189.]
 [196. 191. 190.]
 ...
 [112. 120. 127.]
 [109. 117. 123.]
 [ 69.  77.  81.]]
i 269


Images:  [[ 64.  39.  11.]
 [ 42.  25.   7.]
 [ 46.  36.  30.]
 ...
 [164. 157. 170.]
 [152. 144. 163.]
 [156. 145. 169.]] 
 269  :  [[ 64.  39.  11.]
 [ 42.  25.   7.]
 [ 46.  36.  30.]
 ...
 [164. 157. 170.]
 [152. 144. 163.]
 [156. 145. 169.]]
i 270


Images:  [[ 34.  13.   9.]
 [ 27.   8.   1.]
 [ 34.  17.   7.]
 ...
 [174. 184. 196.]
 [155. 165. 164.]
 [112. 121. 110.]] 
 270  :  [[ 34.  13.   9.]
 [ 27.   8.   1.]
 [ 34.  17.   7.]
 ...
 [174. 184. 196.]
 [155. 165. 164.]
 [112

In [51]:
# print array sample
images_array[69]

array([[168., 145., 129.],
       [170., 146., 130.],
       [171., 148., 132.],
       ...,
       [102., 139., 180.],
       [100., 134., 169.],
       [149., 180., 210.]])

In [52]:
# add the mask data as the prediction class
img_path = directory + "/" + directory + "_mask.png"
img = cv2.imread(img_path)
res = cv2.resize(img, dsize=(240, 240), interpolation=cv2.INTER_CUBIC)
gray = cv2.cvtColor(res, cv2.COLOR_BGR2GRAY)

img_array = img_to_array(gray)
# print(img_array)
print(img_array.shape)
predict_array = img_array.reshape(57600, 1)
print(predict_array.shape)


(240, 240, 1)
(57600, 1)


In [53]:
# assign 240 images for training and 60 for testing

y_train = np.empty([240, 57600, 1], dtype="float")

for i in range (0, 240):
    y_train[i]=predict_array


y_test = np.empty([60,57600, 1], dtype="float")

for i in range (0, 60):
    y_test[i]=predict_array

In [54]:
print(y_train.shape)
print(y_test.shape)

(240, 57600, 1)
(60, 57600, 1)


In [55]:
X_test = np.empty([60, 57600, 3], dtype="float")
X_train = np.empty([240, 57600, 3], dtype="float")

j=0
k=0

for i in range (0, 300):
    if(i%5==0):
        X_test[j] = images_array[i]
        j=j+1
    else:
        X_train[k] = images_array[i]
        k=k+1

In [57]:
# Normalize the pixel values
X_test/=255
X_train/=255
y_test/=255
y_train/=255


In [58]:
# reshape the data
X_train = X_train.reshape(240,240,240,3)
X_test = X_test.reshape(60,240,240,3)
y_train = y_train.reshape(240,240,240,1)
y_test = y_test.reshape(60,240,240,1)

In [59]:
# pre-process images data for the segmentation model
BACKBONE = 'resnet34'
preprocess_input = sm.get_preprocessing(BACKBONE)

x_train, y_train, x_val, y_val = X_train, y_train, X_test, y_test

x_train = preprocess_input(x_train)
x_val = preprocess_input(x_val)

In [60]:
# compile the model

model.compile(
    'Adam',
    loss=sm.losses.bce_jaccard_loss,
    metrics=[sm.metrics.iou_score],
)

In [61]:
# train the model
model.fit(
   x=x_train,
   y=y_train,
   batch_size=4,
   epochs=2,
   validation_data=(x_val, y_val),
)

Train on 240 samples, validate on 60 samples
Epoch 1/2
240/240 [==============================] - 92s 385ms/step - loss: 0.1527 - iou_score: 0.9311 - val_loss: 0.5465 - val_iou_score: 0.7058
Epoch 2/2
240/240 [==============================] - 90s 373ms/step - loss: 0.0251 - iou_score: 0.9845 - val_loss: 0.2128 - val_iou_score: 0.8717


In [119]:
model.save("skyPixelModel.h5")

### Model prediction is shown in SkyPixelPredict.ipynb